---
apiVersion: v1
kind: Secret
metadata:
  name: psql-backup-s3
data:
  POSTGRES_USER:            # PSQL USERNAME
  POSTGRES_PASSWORD:        # PSQL PASSWORD
  AWS_ACCESS_KEY_ID:        # AWS IAM USER ID
  AWS_SECRET_ACCESS_KEY:    # AWS IAM USER KEY
---
